package app.view;

import app.model.Category;

import javax.swing.*;
import java.awt.*;

public class CategoryPanel {
    private JPanel addNewCategoryBtn;
    private JPanel categoriesPane;
    private JButton backBtn;
    private JComboBox<Category> categoriesBox;

    public CategoryPanel() {
        categoriesBox = new JComboBox<>();
        categoriesPane.add(categoriesBox, BorderLayout.NORTH);
    }

    public JPanel getAddNewCategoryBtn() {
        return addNewCategoryBtn;
    }

    public JComboBox<Category> getCategoriesBox() {
        return categoriesBox;
    }

    public JPanel getCategoriesPane() {
        return categoriesPane;
    }

    public JButton getBackBtn() {
        return backBtn;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        categoriesPane = new JPanel();
        categoriesPane.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        categoriesPane.add(panel1, BorderLayout.WEST);
        addNewCategoryBtn = new JPanel();
        addNewCategoryBtn.setLayout(new BorderLayout(0, 0));
        addNewCategoryBtn.setBackground(new Color(-1));
        addNewCategoryBtn.setPreferredSize(new Dimension(135, 40));
        panel1.add(addNewCategoryBtn, BorderLayout.SOUTH);
        final JLabel label1 = new JLabel();
        label1.setIcon(new ImageIcon(getClass().getResource("/app/images/add-button-inside-black-circle.png")));
        label1.setText("Utwórz nowy");
        addNewCategoryBtn.add(label1, BorderLayout.WEST);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        categoriesPane.add(panel2, BorderLayout.EAST);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        categoriesPane.add(panel3, BorderLayout.SOUTH);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel3.add(panel4, BorderLayout.CENTER);
        backBtn = new JButton();
        backBtn.setBackground(new Color(-1));
        backBtn.setText("Powrót");
        panel4.add(backBtn, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return categoriesPane;
    }
}
