package app.view;

import javax.swing.*;
import java.awt.*;

public class CreateCategory {
    private JTextField categoryNameField;
    private JButton addCategory;
    private JPanel addCategoryPane;

    public JTextField getCategoryNameField() {
        return categoryNameField;
    }

    public JButton getAddCategory() {
        return addCategory;
    }

    public JPanel getAddCategoryPane() {
        return addCategoryPane;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        addCategoryPane = new JPanel();
        addCategoryPane.setLayout(new GridBagLayout());
        addCategoryPane.setPreferredSize(new Dimension(150, 30));
        categoryNameField = new JTextField();
        categoryNameField.setPreferredSize(new Dimension(200, 30));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addCategoryPane.add(categoryNameField, gbc);
        addCategory = new JButton();
        addCategory.setText("Dodaj");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        addCategoryPane.add(addCategory, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return addCategoryPane;
    }
}
