package app.view;

import javax.swing.*;
import java.awt.*;

public class ToyPanel {
    private JPanel toysPanel;
    private JPanel addNewBtn;

    public ToyPanel() {
        addNewBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }

    public JPanel getToysPanel() {
        return toysPanel;
    }

    public JPanel getAddNewBtn() {
        return addNewBtn;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        toysPanel = new JPanel();
        toysPanel.setLayout(new GridBagLayout());
        toysPanel.setBackground(new Color(-1));
        toysPanel.setMinimumSize(new Dimension(566, 372));
        toysPanel.setOpaque(false);
        toysPanel.setPreferredSize(new Dimension(572, 372));
        addNewBtn = new JPanel();
        addNewBtn.setLayout(new GridBagLayout());
        addNewBtn.setBackground(new Color(-1));
        addNewBtn.setPreferredSize(new Dimension(135, 40));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        toysPanel.add(addNewBtn, gbc);
        final JLabel label1 = new JLabel();
        label1.setIcon(new ImageIcon(getClass().getResource("/app/images/add-button-inside-black-circle.png")));
        label1.setText("Utwórz nowy");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        addNewBtn.add(label1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return toysPanel;
    }
}
